### ISSUE TITLE
Rename Connect-Process to Attach-Process

### ISSUE THREAD

**Issue by dronkoff** [Microsoft/DbgShell#10]
Attach is more recognizable verb, I guess.

**Comment by jazzdelightsme** [comment]
Unfortunately, `Attach` is not a standard PowerShell verb. However, a good compromise might be to add an alias (I believe you can use non-standard verbs in aliases without getting warnings).

**Comment by dronkoff** [comment]
I think most of the people who will come and try DbgShell will have more debugging experience than PowerShell so attach verb will be more close to them. But agree - aliases are good.
