### ISSUE TITLE
Read-DbgDisassembly doesn't resolve Address from Piped Get-DbgSymbol

### ISSUE THREAD

**Issue by Zhentar** [Microsoft/DbgShell#37]
`Get-DbgSymbol "MyClass::MyFunction" | Read-DbgDisassembly` returns the error "Read-DbgDisassembly : Cannot process argument transformation on parameter 'Address'. Could not convert 'MS.Dbg.DbgPublicSymbol' to an address.". So I tried sticking a `Select Address` in there, but that didn't work either. 

`%{ $_.Address.ToString("X8") }` got the job done but doesn't seem like the intended workflow.

**Comment by jazzdelightsme** [comment]
Thanks for the feedback!

The obvious missing thing here is the `ValueFromPipelineByPropertyName` property.

But, out of curiosity, if you actually sent in a `DbgSymbol` object, would you prefer that `Read-DbgDisassembly` disassemble the whole function by default? (I'm leaning that way...) Or would you prefer to stick to "just disassemble a little bit unless you pass -`WholeFunction` param in that case?

BTW, the trick to get it to work with `select` is to also use `-ExpandProperty`.

**Comment by Zhentar** [comment]
`WholeFunction` is what I wanted, but it wasn't hard to find or type so I don't have a strong opinion either way 😃

**Comment by jazzdelightsme** [comment]
I had wanted to add another parameter set that specifically takes a `DbgSymbol` object, which does the whole function, but the parameter set management turned out to be way crazier than expected (and maybe not possible?), so we'll have stick with using `-WholeFunction` (or just `uf`).
