### ISSUE TITLE
Figure out how to get CI builds, host a binary release

### ISSUE THREAD

**Issue by jazzdelightsme** [Microsoft/DbgShell#4]

**Comment by dronkoff** [comment]
Check this link: https://docs.microsoft.com/en-us/vsts/build-release/actions/ci-build-github

**Comment by jazzdelightsme** [comment]
Thank you, @dronkoff! I ended up using appveyor (another friend uses it), but VSTS looks like a good option, too.

First binary release is available: https://aka.ms/DbgShell-latest
