### ISSUE TITLE
captured stdout output is garbled

### ISSUE THREAD

**Issue by wangzq** [microsoft/DbgShell#95]
Running `git --version` directly returns correct result, but if I assign it to a variable then it will be garbled: `$x = git --version; $x`.

**Comment by jazzdelightsme** [comment]
Whoa! I was able to repro; that is a weird bug. Thanks for the report, I will hopefully have a minute to look into it soon.

**Comment by jazzdelightsme** [comment]
Fixed in 7cf3747681eeb6ac320e0e638b753c18612edfcb (you can read the commit message for more details).

Thank you for the report @wangzq!
